# Generated by Django 3.2.7 on 2021-11-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alttag', models.CharField(max_length=128)),
                ('media_url', models.CharField(max_length=128)),
                ('priority', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'header_banner',
            },
        ),
    ]
