# Generated by Django 3.2.7 on 2021-11-25 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HeaderApp', '0004_alter_headerbanner_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerbanner',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
