# Generated by Django 3.2.7 on 2021-11-25 10:52

import FunctionManger.DateTimeManager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeaderApp', '0006_alter_headerbanner_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerbanner',
            name='date_time',
            field=models.DateTimeField(blank=True, default=FunctionManger.DateTimeManager.get_date_time_db),
        ),
    ]
